# Generated by Django 5.0.1 on 2024-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentification', '0002_mycr_delete_mycrrr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycr',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
